import { type NextPage } from "next";
import Head from "next/head";

import Navbar from "../components/Navbar";
import Sidebar from "../components/Sidebar";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex flex-col min-h-screen p-x-8 bg-white">
				<Navbar />
				<div className="flex justify-between">
					<Sidebar active="Guía Sansano"/>
				</div>
      </main>
    </>
  );
};


export default Home;
